"""empty message

Revision ID: 06d4d0dd11bc
Revises: d435d591f1b4
Create Date: 2026-07-10 04:40:03.641324

"""

from typing import Sequence, Union

import sqlalchemy as sa
import uuid_utils
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "06d4d0dd11bc"
down_revision: Union[str, Sequence[str], None] = "d435d591f1b4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alert",
        sa.Column("id", sa.UUID(), default=uuid_utils.uuid7, nullable=False),
        sa.Column("file_id", sa.Uuid(), nullable=False),
        sa.Column("level", sa.String(length=50), nullable=False),
        sa.Column("message", sa.String(length=500), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["file.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("alert")
    # ### end Alembic commands ###
